### ISSUE TITLE
v2.7.1 登录接口收到toekn 但是无法自动重定向到首页，手动进入首页后提示 404

### ISSUE THREAD

**Issue by geekyouth** [wojiushixiaobai/dataease#1]
v2.7.1 登录接口收到toekn 但是无法自动重定向到首页，手动进入首页后提示 404
![image](https://github.com/wojiushixiaobai/dataease/assets/12899262/8e116f5e-9055-4c27-8593-525874f751cf)

![image](https://github.com/wojiushixiaobai/dataease/assets/12899262/56b57d1b-cf78-448c-9de0-801841ce6682)

**Comment by geekyouth** [comment]
![image](https://github.com/wojiushixiaobai/dataease/assets/12899262/081f5253-ed95-4269-b04c-5097b18834cf)
![image](https://github.com/wojiushixiaobai/dataease/assets/12899262/11d3cf21-5fec-4c79-8b42-4692afdab573)

**Comment by geekyouth** [comment]
dockerfile 构建镜像使用的 dataease 版本号为 2.7.0，然而 dockerhub 查到的可用版本只有 latest | v2.7.1 | v2.6.1，理论上使用 image: wojiushixiaobai/dataease:v2.7.1 应该正常使用全部功能。

![image](https://github.com/wojiushixiaobai/dataease/assets/12899262/8b9a932c-3984-4deb-8c60-7cb632120d0c)

**Comment by wojiushixiaobai** [comment]
试试用 registry.cn-qingdao.aliyuncs.com/dataease/dataease:v2.7.1 这个镜像看看，由于官方没有提供完整的构建 Dockerfile，这个是我参考开发文档写的，我得 debug 下

**Comment by geekyouth** [comment]
尝试使用 docker-compose 启动 v2.7.1 v2.6.1 v2.6.0 三个版本的 docker 镜像，都出现大量 404 xpack 错误，WEB-UI 某些功能无法使用，期待修复，谢谢。

**Comment by wojiushixiaobai** [comment]
@geekyouth 试试最新版本 v2.10.0 应该都修复了。
